language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; sudo apt-get update && sudo apt-get install -y libgsl0ldbl libgsl0-dev swig doxygen python-pip; 
  - if [ "$CXX" = "g++" && $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install brew install gsl swig doxygen python-pip; pip install sphinx breathe; fi

install: make all

script: bin/TutorialLevel1 docu/turorial/TutorialLevel1Params.data

os:
  - linux
  - osx
